import sys

import networkx as nx
import numpy
from PyQt5.QtCore import QRect, QMetaObject, QCoreApplication
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QApplication, QWidget, QMainWindow, QVBoxLayout, QHBoxLayout, QSizePolicy, \
    QPushButton, QFileDialog, QGridLayout, QInputDialog, QMessageBox, QTextEdit, QTabWidget, QTextBrowser, QLabel, \
    QLineEdit, QMenuBar, QStatusBar
from PyQt5.uic.properties import QtWidgets, QtCore, QtGui
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from pip._vendor.msgpack.fallback import xrange


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1214, 776)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QRect(0, 60, 1191, 661))
        font = QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QWidget()
        self.tab_1.setObjectName("tab_1")
        self.textBrowser_3 = QTextBrowser(self.tab_1)
        self.textBrowser_3.setGeometry(QRect(10, 10, 561, 521))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.widget_2 = QWidget(self.tab_1)
        self.widget_2.setGeometry(QRect(580, 10, 591, 521))
        self.widget_2.setObjectName("widget_2")
        self.pushButton_3 = QPushButton(self.tab_1)
        self.pushButton_3.setGeometry(QRect(10, 550, 561, 61))
        font = QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QPushButton(self.tab_1)
        self.pushButton.setGeometry(QRect(590, 550, 271, 61))
        font = QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QPushButton(self.tab_1)
        self.pushButton_2.setGeometry(QRect(880, 550, 291, 61))
        font = QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser = QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QRect(300, 10, 281, 531))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QRect(10, 10, 281, 531))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.widget = QWidget(self.tab_2)
        self.widget.setGeometry(QRect(590, 10, 581, 531))
        self.widget.setObjectName("widget")
        self.pushButton_4 = QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QRect(10, 560, 571, 61))
        font = QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QRect(590, 560, 271, 61))
        font = QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QRect(880, 560, 291, 61))
        font = QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.tab_2, "")
        self.label = QLabel(self.centralwidget)
        self.label.setGeometry(QRect(220, 30, 371, 21))
        font = QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QRect(600, 20, 271, 31))
        font = QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QRect(0, 0, 1214, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "Запустить работу МТ"))
        self.pushButton.setText(_translate("MainWindow", "Построить график"))
        self.pushButton_2.setText(_translate("MainWindow", "Остановить построение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Одноленточная МТ"))
        self.pushButton_4.setText(_translate("MainWindow", "Запустить работу МТ"))
        self.pushButton_5.setText(_translate("MainWindow", "Построить график"))
        self.pushButton_6.setText(_translate("MainWindow", "Остановить построение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Многоленточная МТ"))
        self.label.setText(_translate("MainWindow", "L =  { (01)^n c (10)^n | n >= 1}"))


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
